"""Pydantic schemas for registration, authentication, and analytics."""

from __future__ import annotations

import re
from datetime import datetime
from enum import Enum
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, EmailStr, Field, field_validator, model_validator

from ...schemas.user import UserOut

PASSWORD_PATTERN = re.compile(
    r"^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[^A-Za-z0-9]).{12,}$"
)
PASSWORD_ERROR = "Password must be at least 12 characters and include uppercase, lowercase, digit, and special character."


class UserRole(str, Enum):
    """Supported roles."""

    CUSTOMER = "Customer"
    DEVELOPER = "Developer"
    ADMIN = "Admin"


class RegisterStep1In(BaseModel):
    """Incoming payload for step 1 of registration."""

    first_name: str = Field(..., max_length=50)
    last_name: str = Field(..., max_length=50)
    email: EmailStr
    password: str
    confirm_password: str
    terms_accepted: Optional[bool] = None
    role: UserRole
    recaptcha_token: str

    @field_validator("first_name", "last_name")
    @classmethod
    def _strip_names(cls, value: str) -> str:
        value = value.strip()
        if not value:
            raise ValueError("Required")
        return value

    @field_validator("password")
    @classmethod
    def _validate_password(cls, value: str) -> str:
        if not PASSWORD_PATTERN.match(value):
            raise ValueError(PASSWORD_ERROR)
        return value

    @model_validator(mode="after")
    def _check_confirm_password(self) -> "RegisterStep1In":
        if self.password != self.confirm_password:
            raise ValueError("Passwords do not match.")
        return self


class RegisterStep1Out(BaseModel):
    """Response payload for step 1."""

    temp_token: str


class RegisterStep2In(BaseModel):
    """Incoming payload for step 2 of registration."""

    company_name: str = Field(..., max_length=100)
    profile: Dict[str, Any] = Field(default_factory=dict)

    @field_validator("company_name")
    @classmethod
    def _strip_company(cls, value: str) -> str:
        value = value.strip()
        if not value:
            raise ValueError("Company name is required.")
        return value


class RegisterStep2Out(BaseModel):
    """Response payload for completing registration."""

    access_token: str
    refresh_token: Optional[str]
    expires_at: Optional[datetime]
    user: UserOut


class LoginRequest(BaseModel):
    """Incoming payload to authenticate an existing user."""

    email: EmailStr
    password: str
    recaptcha_token: Optional[str] = None


class RefreshRequest(BaseModel):
    """Payload for exchanging a refresh token for a new access token."""

    refresh_token: str


class TokenResponse(BaseModel):
    """JWT token response structure."""

    access_token: str
    token_type: str = "bearer"
    expires_at: Optional[datetime] = None
    refresh_token: Optional[str] = None


class AnalyticsEventIn(BaseModel):
    """Analytics tracking payload."""

    event_type: str
    step: Optional[str] = None
    role: Optional[UserRole] = None
    details: Optional[Dict[str, Any]] = Field(default_factory=dict)

    @field_validator("event_type")
    @classmethod
    def _require_event_type(cls, value: str) -> str:
        value = value.strip()
        if not value:
            raise ValueError("event_type is required")
        return value


# Resolve forward references generated by postponed evaluation of annotations.
RegisterStep1In.model_rebuild()
RegisterStep1Out.model_rebuild()
RegisterStep2In.model_rebuild()
RegisterStep2Out.model_rebuild()
LoginRequest.model_rebuild()
RefreshRequest.model_rebuild()
TokenResponse.model_rebuild()
AnalyticsEventIn.model_rebuild()


# Ensure forward references are resolved when `from __future__ import annotations` is active.
RegisterStep1In.model_rebuild()
RegisterStep2In.model_rebuild()
RegisterStep2Out.model_rebuild()
TokenResponse.model_rebuild()
AnalyticsEventIn.model_rebuild()


class LoginResponse(BaseModel):
    """Canonical login response."""

    access_token: str
    refresh_token: str
    token_type: str = "bearer"
    email_verified: bool = True


class MeProfile(BaseModel):
    """Canonical profile payload for /auth/me."""

    id: str
    email: EmailStr
    display_name: str
    status: str
    created_at: datetime
    last_login: Optional[datetime] = None
    first_name: Optional[str] = None
    last_name: Optional[str] = None
    company_name: Optional[str] = None
    email_verified: Optional[bool] = None


class MeSummary(BaseModel):
    """Summary payload for /auth/me."""

    projects_count: int = 0
    recent_activity: List[Dict[str, Any]] = Field(default_factory=list)
    system_status: str = "ok"


class MeResponse(BaseModel):
    """Canonical user profile response."""

    role: str
    profile: MeProfile
    summary: Optional[MeSummary] = None


class ErrorResponse(BaseModel):
    """Canonical error response."""

    detail: str


# ---------------------------------------------------------------------------
# Developer registration schemas
# ---------------------------------------------------------------------------


class DeveloperRegisterIn(BaseModel):
    """Extended registration payload for developers."""

    first_name: str = Field(..., max_length=50)
    last_name: str = Field(..., max_length=50)
    email: EmailStr
    password: str
    confirm_password: str
    terms_accepted: bool
    company_name: str = Field(default="", max_length=100)
    recaptcha_token: Optional[str] = None
    # Developer-specific fields
    organization: Optional[str] = Field(default=None, max_length=200)
    use_case: Optional[str] = Field(default=None, max_length=64)
    website_url: Optional[str] = Field(default=None, max_length=500)
    github_url: Optional[str] = Field(default=None, max_length=500)
    developer_terms_accepted: bool = False

    @field_validator("first_name", "last_name")
    @classmethod
    def _strip_names(cls, value: str) -> str:
        value = value.strip()
        if not value:
            raise ValueError("Required")
        return value

    @field_validator("password")
    @classmethod
    def _validate_password(cls, value: str) -> str:
        if not PASSWORD_PATTERN.match(value):
            raise ValueError(PASSWORD_ERROR)
        return value

    @model_validator(mode="after")
    def _check_passwords_and_terms(self) -> "DeveloperRegisterIn":
        if self.password != self.confirm_password:
            raise ValueError("Passwords do not match.")
        if not self.terms_accepted:
            raise ValueError("Terms must be accepted.")
        if not self.developer_terms_accepted:
            raise ValueError("Developer terms must be accepted.")
        return self


class DeveloperRegisterOut(BaseModel):
    """Response after developer registration completes."""

    access_token: str
    refresh_token: Optional[str] = None
    email_verified: bool = False
    message: str = "Developer account created. Please verify your email."


# ---------------------------------------------------------------------------
# Admin invite / registration schemas
# ---------------------------------------------------------------------------


class AdminInviteIn(BaseModel):
    """Payload for an admin to invite a new admin."""

    target_email: EmailStr
    expiry_hours: int = Field(default=48, ge=1, le=168)


class AdminInviteOut(BaseModel):
    """Response after successfully creating an admin invite."""

    invite_id: str
    target_email: str
    expires_at: datetime
    message: str = "Admin invite sent."


class AdminInviteListOut(BaseModel):
    """Single invite entry for listing."""

    id: str
    target_email: str
    invited_by: Optional[str] = None
    created_at: datetime
    expires_at: datetime
    used_at: Optional[datetime] = None
    revoked_at: Optional[datetime] = None


class AdminRegisterIn(BaseModel):
    """Registration payload for admin invite-based signup."""

    invite_token: str = Field(..., min_length=10, max_length=255)
    first_name: str = Field(..., max_length=50)
    last_name: str = Field(..., max_length=50)
    email: EmailStr
    password: str
    confirm_password: str
    terms_accepted: bool
    company_name: str = Field(default="", max_length=100)

    @field_validator("first_name", "last_name")
    @classmethod
    def _strip_names(cls, value: str) -> str:
        value = value.strip()
        if not value:
            raise ValueError("Required")
        return value

    @field_validator("password")
    @classmethod
    def _validate_password(cls, value: str) -> str:
        if not PASSWORD_PATTERN.match(value):
            raise ValueError(PASSWORD_ERROR)
        return value

    @model_validator(mode="after")
    def _check_passwords_and_terms(self) -> "AdminRegisterIn":
        if self.password != self.confirm_password:
            raise ValueError("Passwords do not match.")
        if not self.terms_accepted:
            raise ValueError("Terms must be accepted.")
        return self


class AdminRegisterOut(BaseModel):
    """Response after admin registration completes."""

    access_token: str
    refresh_token: Optional[str] = None
    email_verified: bool = True
    message: str = "Admin account created."


# Resolve forward references
LoginResponse.model_rebuild()
MeProfile.model_rebuild()
MeSummary.model_rebuild()
MeResponse.model_rebuild()
ErrorResponse.model_rebuild()
DeveloperRegisterIn.model_rebuild()
DeveloperRegisterOut.model_rebuild()
AdminInviteIn.model_rebuild()
AdminInviteOut.model_rebuild()
AdminInviteListOut.model_rebuild()
AdminRegisterIn.model_rebuild()
AdminRegisterOut.model_rebuild()
