name: CI & Deploy (Heroku autorisen)

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Diagnostics (deploy-heroku)
        run: |
          echo "RUNNING DIAGNOSTICS"
          echo "GITHUB_REPOSITORY=$GITHUB_REPOSITORY"
          echo "GITHUB_REF=$GITHUB_REF"
          echo "GITHUB_ACTOR=$GITHUB_ACTOR"
          if [ -n "${GITHUB_TOKEN-}" ]; then echo "GITHUB_TOKEN is set"; else echo "GITHUB_TOKEN is NOT set"; fi
      - uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - run: pip install -e ./backend
      - run: python -c "import fastapi, uvicorn; print('smoke ok')" # quick import test

  deploy:
    needs: test
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU (for multi-platform builds, optional)
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Heroku Container Registry
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          echo "$HEROKU_API_KEY" | docker login --username=_ --password-stdin registry.heroku.com

      - name: Build Docker image
        run: |
          docker build -t registry.heroku.com/${{ secrets.HEROKU_APP_NAME }}/web .

      - name: Push Docker image
        run: |
          docker push registry.heroku.com/${{ secrets.HEROKU_APP_NAME }}/web

      - name: Install Heroku CLI
        run: |
          curl https://cli-assets.heroku.com/install.sh | sh

      - name: Release to Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          heroku container:release web --app ${{ secrets.HEROKU_APP_NAME }}

      - name: Wait for release
        run: |
          echo "Waiting 6s for Heroku router to route to the new release"
          sleep 6

      - name: Post-release smoke test (debug)
        env:
          APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          set -euo pipefail
          # Prefer the Heroku app's canonical web URL (handles apps with suffixes or review apps).
          APP_WEB_URL=$(heroku apps:info --app "$APP_NAME" --json 2>/dev/null | python -c 'import sys,json;obj=json.load(sys.stdin);print(obj.get("app",{}).get("web_url","").rstrip("/"))' || true)

          if [ -n "$APP_WEB_URL" ]; then
            BASE="$APP_WEB_URL"
          else
            BASE="https://${APP_NAME}.herokuapp.com"
          fi

          TARGETS=("${BASE}/api/health" "${BASE}/alive" "${BASE}/")

          for tgt in "${TARGETS[@]}"; do
            echo "Checking $tgt"
            for i in 1 2 3 4 5 6; do
              echo "Attempt $i: GET $tgt"
              tmp=$(mktemp)
              http_code=$(curl -sS -w '%{http_code}' -o "$tmp" "$tgt" -m 10 || true)
              echo "HTTP $http_code"
              if [ "$http_code" = "200" ]; then
                echo "OK: $tgt returned 200"
                cat "$tmp"
                rm -f "$tmp"
                exit 0
              fi
              echo "--- response (truncated to 4k) ---"
              head -c 4096 "$tmp" || true
              echo "\n--- end response ---"
              rm -f "$tmp"
              sleep 2
            done
            echo "$tgt did not return 200 after retries, trying next target"
          done

          echo "All targets failed — dumping recent Heroku logs for diagnosis"
          # Install and show Heroku logs (requires HEROKU_API_KEY set in secrets)
          heroku logs --app "$APP_NAME" --num 150 || true

          echo "Smoke test failed: none of the targets responded with 200"
          exit 1
