#!/bin/bash
echo "🚀 Starting CapeControl with Stripe Integration..."
echo ""
echo "📋 Configuration Status:"
echo "✅ Stripe Secret Key: Configured"
echo "✅ Stripe Publishable Key: Configured" 
echo "✅ Stripe Webhook Secret: whsec_mJ6dDsOWAlODg2yc8MM5tUgFZKFTzfOY"
echo ""
echo "🔗 Endpoints Available:"
echo "   📊 API Docs: http://localhost:8000/docs"
echo "   🔍 Stripe Status: http://localhost:8000/api/stripe/status"
echo "   💳 Checkout Session: http://localhost:8000/api/stripe/create-checkout-session"
echo "   🪝 Webhook: http://localhost:8000/api/stripe/webhook"
echo ""
echo "🎯 Stripe Dashboard Test:"
echo "   1. Go to: https://dashboard.stripe.com/test/workbench/webhooks"
echo "   2. Find your 'sophisticated-excellence' webhook"
echo "   3. Click 'Send test events'"
echo "   4. Test checkout.session.completed event"
echo ""
echo "⏯️  Starting server on port 8000..."
echo "   Press Ctrl+C to stop"
echo ""

python3 -m uvicorn app.main:app --host 0.0.0.0 --port 8000 --log-level warning
