import React from "react";
import { Link } from "react-router-dom";
import TopNav from "../../components/nav/TopNav";
import logoUrl from "../../assets/capecontrol-logo.png";
import BuildBadge from "../../components/version/BuildBadge";

const DeveloperInfoPage: React.FC = () => {
  return (
    <div className="landing">
      <TopNav onOpenSupport={() => {}} />
      <main className="landing__main">
        <section className="section" style={{ paddingTop: "6rem" }}>
          <div style={{ maxWidth: 860, margin: "0 auto" }}>
            <span className="badge badge--accent">Developer Information</span>
            <h1 style={{ fontSize: "2.4rem", lineHeight: 1.2, marginBottom: "1rem" }}>
              CapeControl — Developer Information Sheet
            </h1>
            <p style={{ opacity: 0.7, marginBottom: "2.5rem" }}>
              Information for Developers Considering CapeControl &middot; Last Updated: February 14, 2026
            </p>

            <p>
              Thank you for your interest in building AI agents with CapeControl. This document
              gives you a straightforward overview of what joining our platform involves — the
              opportunities, the commitments, and the risks — so you can make an informed decision
              before signing our Terms and Conditions.
            </p>
            <p style={{ opacity: 0.7, fontStyle: "italic" }}>
              Please read this document alongside the full Terms and Conditions, which govern the
              legal relationship between you and CapeControl.
            </p>

            {/* ---- What CapeControl Does ---- */}
            <h2 style={{ marginTop: "3rem" }}>What CapeControl Does</h2>
            <p>
              CapeControl is a platform where businesses and individuals access AI agents to handle
              tasks such as automation, content creation, data analysis, and workflow management.
              These agents are built by independent developers like you and made available to users
              through subscription pricing.
            </p>
            <p>
              As a developer, you build agents for the platform and earn a share of the revenue
              those agents generate.
            </p>

            {/* ---- How the Developer Relationship Works ---- */}
            <h2 style={{ marginTop: "3rem" }}>How the Developer Relationship Works</h2>
            <p>
              You join CapeControl as an independent contractor, not an employee. This means:
            </p>
            <ul style={{ paddingLeft: "1.5rem", lineHeight: 1.8 }}>
              <li>You set your own schedule and work remotely.</li>
              <li>
                You are responsible for your own taxes, insurance, national insurance or equivalent
                contributions, and compliance with applicable laws.
              </li>
              <li>
                CapeControl does not provide employment benefits, holiday pay, sick pay, or pension
                contributions.
              </li>
              <li>No minimum amount of work or revenue is guaranteed.</li>
            </ul>
            <p>
              You build AI agents based on Project Briefs provided by CapeControl. Each brief
              specifies the scope, requirements, timeline, and compensation terms for that project.
            </p>

            {/* ---- Compensation ---- */}
            <h2 style={{ marginTop: "3rem" }}>Compensation: Revenue Sharing</h2>
            <p>
              Your primary compensation is a percentage of the net revenue generated by the AI agent
              you build.
            </p>
            <h3>How it works:</h3>
            <ol style={{ paddingLeft: "1.5rem", lineHeight: 1.8 }}>
              <li>
                Users pay CapeControl to access your agent (via subscription fees).
              </li>
              <li>
                CapeControl deducts platform operating costs (hosting, infrastructure, payment
                processing, and support) from gross revenue to arrive at net revenue.
              </li>
              <li>You receive your agreed percentage of net revenue.</li>
            </ol>

            <h3 style={{ marginTop: "1.5rem" }}>Example (illustrative only)</h3>
            <div style={{ overflowX: "auto" }}>
              <table
                style={{
                  width: "100%",
                  borderCollapse: "collapse",
                  marginTop: "0.75rem",
                  marginBottom: "1.5rem",
                }}
              >
                <thead>
                  <tr>
                    <th
                      style={{
                        textAlign: "left",
                        padding: "0.75rem 1rem",
                        borderBottom: "1px solid rgba(255,255,255,0.15)",
                        opacity: 0.8,
                      }}
                    >
                      Item
                    </th>
                    <th
                      style={{
                        textAlign: "right",
                        padding: "0.75rem 1rem",
                        borderBottom: "1px solid rgba(255,255,255,0.15)",
                        opacity: 0.8,
                      }}
                    >
                      Amount
                    </th>
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    <td style={{ padding: "0.5rem 1rem", borderBottom: "1px solid rgba(255,255,255,0.07)" }}>
                      Gross monthly revenue from your agent (100 users &times; $10/month)
                    </td>
                    <td style={{ padding: "0.5rem 1rem", textAlign: "right", borderBottom: "1px solid rgba(255,255,255,0.07)" }}>
                      $1,000
                    </td>
                  </tr>
                  <tr>
                    <td style={{ padding: "0.5rem 1rem", borderBottom: "1px solid rgba(255,255,255,0.07)" }}>
                      Platform operating costs (estimated 10%)
                    </td>
                    <td style={{ padding: "0.5rem 1rem", textAlign: "right", borderBottom: "1px solid rgba(255,255,255,0.07)" }}>
                      −$100
                    </td>
                  </tr>
                  <tr>
                    <td style={{ padding: "0.5rem 1rem", borderBottom: "1px solid rgba(255,255,255,0.07)" }}>
                      Net revenue
                    </td>
                    <td style={{ padding: "0.5rem 1rem", textAlign: "right", borderBottom: "1px solid rgba(255,255,255,0.07)" }}>
                      $900
                    </td>
                  </tr>
                  <tr style={{ fontWeight: 600 }}>
                    <td style={{ padding: "0.5rem 1rem" }}>Your share (25%)</td>
                    <td style={{ padding: "0.5rem 1rem", textAlign: "right" }}>$225</td>
                  </tr>
                </tbody>
              </table>
            </div>
            <p style={{ opacity: 0.7, fontSize: "0.9rem" }}>
              <strong>Important:</strong> The revenue share percentage, cost deductions, and payment
              terms are specified in each Project Brief. The 25% figure above is an example only.
              Always review the specific terms for your project.
            </p>

            <h3 style={{ marginTop: "1.5rem" }}>Payment details</h3>
            <ul style={{ paddingLeft: "1.5rem", lineHeight: 1.8 }}>
              <li>
                Earnings are tracked via a developer dashboard.{" "}
                <span className="badge badge--accent" style={{ fontSize: "0.7rem", padding: "2px 8px" }}>
                  Coming Soon
                </span>
              </li>
              <li>Payouts are processed monthly, within 30 days of invoice approval.</li>
              <li>
                Payment methods include bank transfer (additional methods will be added as the
                platform scales).
              </li>
              <li>A minimum payout threshold may apply — this will be specified in your agreement.</li>
              <li>
                Revenue is only earned from monetised usage. Free trials, freemium tiers, and
                promotional access do not generate developer revenue until users convert to paid
                plans.
              </li>
              <li>
                <strong>
                  There is no guaranteed minimum income. If your agent has low adoption, your
                  earnings will reflect that.
                </strong>
              </li>
            </ul>

            {/* ---- What You'll Build ---- */}
            <h2 style={{ marginTop: "3rem" }}>What You'll Build</h2>
            <p>
              CapeControl agents are designed to be context-aware, adaptive, and accessible to
              non-technical users. Typical projects include:
            </p>
            <ul style={{ paddingLeft: "1.5rem", lineHeight: 1.8 }}>
              <li>Chatbots and conversational assistants</li>
              <li>Content generation tools</li>
              <li>Data analysis and forecasting agents</li>
              <li>Task automation and scheduling tools</li>
              <li>Domain-specific assistants (e.g., legal research, customer support)</li>
            </ul>
            <p>
              You'll work primarily in Python, using frameworks and tools such as FastAPI,
              PostgreSQL, Pandas, and various AI/ML libraries. CapeControl provides API
              documentation and integration guides through the developer portal.
            </p>

            {/* ---- Benefits ---- */}
            <h2 style={{ marginTop: "3rem" }}>Benefits of Joining</h2>
            <div
              style={{
                display: "grid",
                gridTemplateColumns: "repeat(auto-fit, minmax(280px, 1fr))",
                gap: "1.5rem",
                marginTop: "1rem",
              }}
            >
              {[
                {
                  title: "Recurring revenue potential",
                  text: "Agents that gain traction generate ongoing income. Unlike one-off freelance projects, successful agents can produce revenue for months or years.",
                },
                {
                  title: "Access to infrastructure and users",
                  text: "CapeControl handles hosting, distribution, billing, and customer support. You focus on building; the platform handles the rest.",
                },
                {
                  title: "Flexibility",
                  text: "Choose projects that match your skills and interests. Work on your own schedule from anywhere.",
                },
                {
                  title: "Transparent tracking",
                  text: "Monitor your agent's usage and earnings through the developer dashboard.",
                },
                {
                  title: "Community and collaboration",
                  text: "Connect with other developers via our community channels. Share knowledge, get feedback, and collaborate on ideas.",
                },
                {
                  title: "Portfolio visibility",
                  text: "With CapeControl's written approval, you may showcase agents you've built in your professional portfolio.",
                },
              ].map((item) => (
                <article
                  key={item.title}
                  style={{
                    background: "rgba(255,255,255,0.04)",
                    border: "1px solid rgba(255,255,255,0.08)",
                    borderRadius: 12,
                    padding: "1.5rem",
                  }}
                >
                  <h3 style={{ fontSize: "1.05rem", marginBottom: "0.5rem" }}>{item.title}</h3>
                  <p style={{ opacity: 0.8, fontSize: "0.95rem", margin: 0 }}>{item.text}</p>
                </article>
              ))}
            </div>

            {/* ---- Risks ---- */}
            <h2 style={{ marginTop: "3rem" }}>Risks and Challenges — Read Carefully</h2>
            <p>
              We want you to enter this relationship with realistic expectations. Below are the
              significant challenges you should weigh.
            </p>
            <div style={{ display: "flex", flexDirection: "column", gap: "1.25rem", marginTop: "1rem" }}>
              {[
                {
                  title: "Your income depends entirely on user adoption",
                  text: "If few people use your agent, you earn little or nothing. CapeControl does not guarantee any minimum revenue. Early-stage agents on a growing platform may take time to gain traction — or may not gain traction at all.",
                },
                {
                  title: "Significant upfront time investment with no guaranteed return",
                  text: "Building an MVP typically requires 20–40+ hours of work. You bear this time cost with no certainty of financial return. While CapeControl may occasionally offer small upfront payments for specific projects, this is not standard and should not be assumed.",
                },
                {
                  title: "You do not own the code you create",
                  text: "All agent code, deliverables, and related intellectual property created under your agreement are owned by CapeControl or its clients. You may not reuse, republish, or redistribute this code without written permission. You retain ownership of any pre-existing code or open-source tools you bring to the project, provided you disclose them properly.",
                },
                {
                  title: "Platform risk",
                  text: "CapeControl is an early-stage platform. Its commercial success is not guaranteed. If user growth is slower than projected, or if the platform encounters financial difficulties, your revenue will be directly affected.",
                },
                {
                  title: "Ongoing maintenance expectations",
                  text: "You may be asked to update or improve your agent based on user feedback, bug reports, or platform changes. Failure to maintain your agent may affect its availability and your revenue share.",
                },
                {
                  title: "Strict confidentiality obligations",
                  text: "You must protect all confidential information related to CapeControl, its clients, and its users. These obligations survive for five years after your agreement ends.",
                },
                {
                  title: "Liability is limited",
                  text: "CapeControl's total liability to you is capped at the revenue your work has generated. This means your financial recourse in any dispute is limited.",
                },
                {
                  title: "Termination",
                  text: "Either party may terminate the agreement with 14 days' written notice. Upon termination, you are paid only for revenue already received from completed work. Ongoing revenue share ceases upon termination unless otherwise specified.",
                },
              ].map((item) => (
                <div
                  key={item.title}
                  style={{
                    background: "rgba(239,68,68,0.06)",
                    border: "1px solid rgba(239,68,68,0.15)",
                    borderRadius: 10,
                    padding: "1.25rem 1.5rem",
                  }}
                >
                  <h3 style={{ fontSize: "1rem", marginBottom: "0.4rem", color: "#fca5a5" }}>
                    {item.title}
                  </h3>
                  <p style={{ opacity: 0.85, fontSize: "0.93rem", margin: 0 }}>{item.text}</p>
                </div>
              ))}
            </div>

            {/* ---- Who This Is For ---- */}
            <h2 style={{ marginTop: "3rem" }}>Who This Is Suited For</h2>
            <p>This opportunity is best suited for developers who:</p>
            <ul style={{ paddingLeft: "1.5rem", lineHeight: 1.8 }}>
              <li>
                Are proficient in Python with experience in AI/ML, API development, or data
                processing.
              </li>
              <li>Understand and accept the risks of revenue-dependent compensation.</li>
              <li>
                Are comfortable working as independent contractors without employment protections.
              </li>
              <li>
                Have the discipline and motivation to deliver quality work on a self-managed
                schedule.
              </li>
              <li>
                Are excited about building practical AI tools and contributing to a growing platform.
              </li>
            </ul>

            <p style={{ marginTop: "1.5rem" }}>
              <strong>This may not be the right fit if you:</strong>
            </p>
            <ul style={{ paddingLeft: "1.5rem", lineHeight: 1.8 }}>
              <li>Need guaranteed, predictable income.</li>
              <li>Are uncomfortable with assigning IP ownership of your work.</li>
              <li>Prefer structured employment with benefits and oversight.</li>
              <li>Cannot commit the upfront time investment without assured compensation.</li>
            </ul>

            {/* ---- Application Process ---- */}
            <h2 style={{ marginTop: "3rem" }}>The Application Process</h2>
            <ol style={{ paddingLeft: "1.5rem", lineHeight: 2.2 }}>
              <li>
                <strong>Register</strong> — Create a developer account through our{" "}
                <Link to="/auth/register" style={{ color: "#93c5fd" }}>
                  registration page
                </Link>
                .
              </li>
              <li>
                <strong>Review and onboarding</strong> — Review and sign the Terms and Conditions,
                and gain access to our APIs and community channels.
              </li>
              <li>
                <strong>Build</strong> — Develop your first AI agent based on an assigned or chosen
                Project Brief.
              </li>
              <li>
                <strong>Launch and earn</strong> — Your agent goes live on the{" "}
                <Link to="/app/marketplace" style={{ color: "#93c5fd" }}>
                  marketplace
                </Link>
                , and you begin earning revenue share from paid usage.
              </li>
              <li>
                <strong>Iterate and grow</strong> — Improve your agent based on feedback, take on
                additional projects, and grow your earnings as the platform scales.
              </li>
            </ol>

            {/* ---- Legal Summary ---- */}
            <h2 style={{ marginTop: "3rem" }}>Key Legal Points (Summary)</h2>
            <p style={{ opacity: 0.7, fontSize: "0.9rem", marginBottom: "1rem" }}>
              This is a summary only. The Terms and Conditions are the binding legal document.
            </p>
            <div style={{ overflowX: "auto" }}>
              <table
                style={{
                  width: "100%",
                  borderCollapse: "collapse",
                  marginBottom: "1.5rem",
                }}
              >
                <thead>
                  <tr>
                    <th
                      style={{
                        textAlign: "left",
                        padding: "0.75rem 1rem",
                        borderBottom: "1px solid rgba(255,255,255,0.15)",
                        opacity: 0.8,
                        width: "30%",
                      }}
                    >
                      Topic
                    </th>
                    <th
                      style={{
                        textAlign: "left",
                        padding: "0.75rem 1rem",
                        borderBottom: "1px solid rgba(255,255,255,0.15)",
                        opacity: 0.8,
                      }}
                    >
                      Summary
                    </th>
                  </tr>
                </thead>
                <tbody>
                  {[
                    ["Status", "Independent contractor. Not an employee."],
                    [
                      "Compensation",
                      "Revenue share from agent usage. No salary, retainer, or minimum guarantee.",
                    ],
                    [
                      "IP ownership",
                      "All deliverables belong to CapeControl or its clients.",
                    ],
                    [
                      "Pre-existing IP",
                      "Remains yours, but must be disclosed and properly licensed.",
                    ],
                    [
                      "Confidentiality",
                      "Strict obligations, lasting 5 years post-termination.",
                    ],
                    [
                      "Data protection",
                      "You must comply with applicable laws (GDPR, CCPA, etc.).",
                    ],
                    [
                      "Termination",
                      "14 days' notice by either party. Payment only for revenue received from completed work.",
                    ],
                    ["Liability cap", "Limited to revenue generated by your work."],
                    [
                      "Dispute resolution",
                      "Refer to Terms and Conditions for governing law and resolution process.",
                    ],
                  ].map(([topic, summary]) => (
                    <tr key={topic}>
                      <td
                        style={{
                          padding: "0.6rem 1rem",
                          borderBottom: "1px solid rgba(255,255,255,0.07)",
                          fontWeight: 500,
                        }}
                      >
                        {topic}
                      </td>
                      <td
                        style={{
                          padding: "0.6rem 1rem",
                          borderBottom: "1px solid rgba(255,255,255,0.07)",
                          opacity: 0.85,
                        }}
                      >
                        {summary}
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>

            {/* ---- Next Steps ---- */}
            <h2 style={{ marginTop: "3rem" }}>Next Steps</h2>
            <div
              style={{
                display: "grid",
                gridTemplateColumns: "repeat(auto-fit, minmax(220px, 1fr))",
                gap: "1rem",
                marginTop: "1rem",
                marginBottom: "2rem",
              }}
            >
              <Link
                to="/auth/register"
                className="btn btn--primary"
                style={{ textAlign: "center" }}
              >
                Register as a Developer
              </Link>
              <Link to="/terms-and-conditions" className="btn btn--ghost" style={{ textAlign: "center" }}>
                Read Terms &amp; Conditions
              </Link>
              <a
                href="mailto:support@cape-control.com"
                className="btn btn--ghost"
                style={{ textAlign: "center" }}
              >
                Ask Questions
              </a>
            </div>

            {/* ---- Our Commitment ---- */}
            <h2 style={{ marginTop: "3rem" }}>Our Commitment</h2>
            <p>
              We are building CapeControl to be a platform where developers can do meaningful work,
              earn fairly, and contribute to making AI accessible and useful. We commit to
              transparency in how revenue is calculated and distributed, clear communication about
              platform developments, and responsive support for our developer community.
            </p>
            <p>We look forward to hearing from you.</p>
            <p style={{ opacity: 0.7 }}>— The CapeControl Team</p>

            {/* ---- Disclaimer ---- */}
            <div
              style={{
                marginTop: "3rem",
                padding: "1.25rem 1.5rem",
                background: "rgba(255,255,255,0.04)",
                border: "1px solid rgba(255,255,255,0.08)",
                borderRadius: 10,
                fontSize: "0.85rem",
                opacity: 0.7,
                lineHeight: 1.7,
              }}
            >
              <strong>Disclaimer:</strong> This document is for informational purposes only and does
              not constitute a contract, offer of employment, or guarantee of income. The Terms and
              Conditions govern the legal relationship between developers and CapeControl. Revenue
              share percentages, cost structures, and payment terms are specified per Project Brief
              and may differ from examples used in this document. For current information, contact
              CapeControl directly at{" "}
              <a href="mailto:support@cape-control.com" style={{ color: "#93c5fd" }}>
                support@cape-control.com
              </a>
              .
            </div>

            {/* Platform status notice */}
            <div
              style={{
                marginTop: "1.5rem",
                marginBottom: "4rem",
                padding: "1rem 1.5rem",
                background: "rgba(79,70,229,0.08)",
                border: "1px solid rgba(79,70,229,0.2)",
                borderRadius: 10,
                fontSize: "0.85rem",
                lineHeight: 1.7,
              }}
            >
              <strong>Platform Status:</strong> Some features described in this document are under
              active development. Features marked{" "}
              <span className="badge badge--accent" style={{ fontSize: "0.7rem", padding: "2px 8px" }}>
                Coming Soon
              </span>{" "}
              are planned and in progress but not yet available. CapeControl is transparent about
              its development stage and will update this document as features launch.
            </div>
          </div>
        </section>
      </main>

      {/* FOOTER */}
      <footer className="footer">
        <div className="footer__content">
          <div className="footer__main">
            <div className="footer__brand">
              <img
                className="footer__logo"
                src={logoUrl}
                alt="CapeControl logo"
                width={44}
                height={44}
                loading="lazy"
              />
              <div>
                <h3>CapeControl</h3>
                <p className="footer__brand-meta">Operated by Cape Craft Projects CC</p>
                <p className="footer__brand-meta">Trading as CapeControl</p>
              </div>
            </div>
            <div className="footer__column">
              <h4>Platform</h4>
              <ul className="footer__links-list">
                <li>
                  <Link to="/">Home</Link>
                </li>
                <li>
                  <Link to="/subscribe">Pricing</Link>
                </li>
              </ul>
            </div>
            <div className="footer__column">
              <h4>Developers</h4>
              <ul className="footer__links-list">
                <li>
                  <Link to="/developers">Developer Info</Link>
                </li>
                <li>
                  <Link to="/auth/register">Register</Link>
                </li>
              </ul>
            </div>
            <div className="footer__column">
              <h4>Company</h4>
              <ul className="footer__links-list">
                <li>
                  <a href="/#about">About</a>
                </li>
                <li>
                  <a href="/#privacy">Privacy Policy</a>
                </li>
                <li>
                  <Link to="/terms-and-conditions">Terms of Service</Link>
                </li>
              </ul>
            </div>
          </div>
          <div className="footer__bottom">
            <p>&copy; {new Date().getFullYear()} CapeControl. All rights reserved.</p>
            <div className="footer__bottom-meta">
              <BuildBadge />
            </div>
          </div>
        </div>
      </footer>
    </div>
  );
};

export default DeveloperInfoPage;
