name: Agents Validate
on:
  pull_request:
    paths: ["agents/**", "scripts/agents_*.py", "config/**"]
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.12' }
      - run: pip install pyyaml
      - run: python3 scripts/agents_validate.py agents/registry.yaml
