name: CI - Health Service

on:
  push:
    branches: [main, modularization/rfc]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test-health:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          echo "Listing workspace files for debugging..."
          ls -R . | sed -n '1,200p'
          if [ -f services/health/requirements.txt ]; then
            echo "Found services/health/requirements.txt — installing from file"
            pip install -r services/health/requirements.txt
          else
            echo "services/health/requirements.txt not found — falling back to explicit installs"
            pip install fastapi==0.95.2 uvicorn[standard]==0.22.0 pytest
          fi
      - name: Run tests
        run: |
          if [ -d services/health/tests ]; then
            pytest services/health/tests -q
          else
            echo "No health tests found (services/health/tests). Skipping tests." 
            exit 0
          fi
