name: Build and publish Docker image

on:
  push:
    branches: [main]
    tags: ["v*", "release-*"]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Check DockerHub secrets
        id: dockerhub-check
        run: |
          # Emit a boolean output `dockerhub_ok=true` when both secrets are present
          if [[ -z "${{ secrets.DOCKERHUB_USERNAME }}" || -z "${{ secrets.DOCKERHUB_TOKEN }}" ]]; then
            echo "dockerhub_ok=false" >> "$GITHUB_OUTPUT"
          else
            echo "dockerhub_ok=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Login to Docker Hub (optional)
        if: steps.dockerhub-check.outputs.dockerhub_ok == 'true'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: NOTE about DockerHub token
        if: steps.dockerhub-check.outputs.dockerhub_ok != 'true'
        run: |
          echo "DOCKERHUB_USERNAME or DOCKERHUB_TOKEN not set - skipping Docker login (this is optional)"

      - name: Determine image name and tag
        id: meta
        run: |
          # Compute values in shell to allow shell fallbacks and robust defaults
          IMAGE_USER="${{ secrets.DOCKERHUB_USERNAME }}"
          IMAGE_REPO="${{ env.DOCKERHUB_REPO }}"
          if [ -z "$IMAGE_REPO" ]; then
            IMAGE_REPO="autorisen"
          fi
          GIT_SHA=$(git rev-parse --short HEAD)
          DATE_UTC=$(date -u +%Y%m%d-%H%M)
          if [ -n "${{ env.DOCKERHUB_VERSION }}" ]; then
            VERSION="${{ env.DOCKERHUB_VERSION }}"
          else
            VERSION="${DATE_UTC}-${GIT_SHA}"
          fi
          echo "IMAGE=${IMAGE_USER}/${IMAGE_REPO}" >> $GITHUB_OUTPUT
          echo "VERSION=${VERSION}" >> $GITHUB_OUTPUT

      - name: Build and push Docker image (backend)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: backend/Dockerfile
          platforms: linux/amd64
          target: backend
          push: true
          tags: |
            ${{ steps.meta.outputs.IMAGE }}:${{ steps.meta.outputs.VERSION }}
            ${{ steps.meta.outputs.IMAGE }}:latest

      - name: Image published
        run: |
          echo "Published ${{ steps.meta.outputs.IMAGE }}:${{ steps.meta.outputs.VERSION }} and :latest"

# Notes:
# - Create repository secrets: DOCKERHUB_USERNAME, DOCKERHUB_TOKEN
# - Optional repo-level envs (in Actions UI) you can set: DOCKERHUB_REPO, DOCKERHUB_VERSION
# - This workflow builds the backend target from `backend/Dockerfile` and pushes two tags.
