name: Build and publish Docker image

on:
  push:
    branches: [main]
    tags:
      - "v*"
      - "release-*"
  workflow_dispatch:

concurrency:
  group: docker-publish-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-push:
    # Only on main or tags
    if: >
      github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      # default repo (can be overridden at repo/env level)
      DOCKERHUB_REPO: autorisen

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # QEMU is only needed for multi-arch; keep it off unless you add more platforms.
      # - name: Setup QEMU
      #   uses: docker/setup-qemu-action@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        if: ${{ github.secrets.DOCKERHUB_USERNAME != '' && github.secrets.DOCKERHUB_TOKEN != '' }}
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Determine image and version
        id: meta
        shell: bash
        run: |
          set -euo pipefail

          # Lower-case for Docker refs
          IMAGE_USER_RAW="${{ secrets.DOCKERHUB_USERNAME }}"
          IMAGE_REPO_RAW="${DOCKERHUB_REPO:-autorisen}"
          IMAGE_USER="$(echo "${IMAGE_USER_RAW}" | tr '[:upper:]' '[:lower:]')"
          IMAGE_REPO="$(echo "${IMAGE_REPO_RAW}" | tr '[:upper:]' '[:lower:]')"

          # Version: explicit override -> tag name -> date+sha
          DATE_UTC="$(date -u +%Y%m%d-%H%M)"
          GIT_SHA="$(git rev-parse --short HEAD)"
          VERSION="${DOCKERHUB_VERSION:-}"
          if [[ -z "${VERSION}" ]]; then
            if [[ "${GITHUB_REF_TYPE:-}" == "tag" ]]; then
              VERSION="${GITHUB_REF_NAME}"
            else
              VERSION="${DATE_UTC}-${GIT_SHA}"
            fi
          fi

          echo "image=${IMAGE_USER}/${IMAGE_REPO}" >> "$GITHUB_OUTPUT"
          echo "version=${VERSION}" >> "$GITHUB_OUTPUT"

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: backend/Dockerfile
          target: backend
          platforms: linux/amd64
          push: true
          tags: |
            ${{ steps.meta.outputs.image }}:${{ steps.meta.outputs.version }}
            ${{ steps.meta.outputs.image }}:latest
          labels: |
            org.opencontainers.image.source=${{ github.repository }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.created=${{ github.event.head_commit.timestamp }}

      - name: Done
        run: echo "Published ${{ steps.meta.outputs.image }}:${{ steps.meta.outputs.version }}"
