name: Build and publish Docker image

on:
  push:
    branches: [main]
    tags: ["v*", "release-*"]
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Diagnostics (docker-publish)
        run: |
          echo "RUNNING DIAGNOSTICS"
          echo "GITHUB_REPOSITORY=$GITHUB_REPOSITORY"
          echo "GITHUB_REF=$GITHUB_REF"
          echo "GITHUB_ACTOR=$GITHUB_ACTOR"
          if [ -n "${GITHUB_TOKEN-}" ]; then echo "GITHUB_TOKEN is set"; else echo "GITHUB_TOKEN is NOT set"; fi

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - id: meta
        name: Determine image name and tag
        run: |
          IMAGE_USER="${{ secrets.DOCKERHUB_USERNAME }}"
          IMAGE_REPO="${DOCKERHUB_REPO:-autorisen}"
          GIT_SHA=$(git rev-parse --short HEAD)
          DATE_UTC=$(date -u +%Y%m%d-%H%M)
          VERSION="${DOCKERHUB_VERSION:-${DATE_UTC}-${GIT_SHA}}"
          echo "IMAGE=${IMAGE_USER}/${IMAGE_REPO}" >> $GITHUB_OUTPUT
          echo "VERSION=${VERSION}" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ${{ steps.meta.outputs.IMAGE }}:${{ steps.meta.outputs.VERSION }}
            ${{ steps.meta.outputs.IMAGE }}:latest

      - name: Image published
        run: echo "Published ${{ steps.meta.outputs.IMAGE }}:${{ steps.meta.outputs.VERSION }} and :latest"
