name: Import sanity & OpenAPI check

concurrency:
  group: import-openapi-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches: [main]

jobs:
  import-sanity:
    name: Import sanity
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install backend deps (best-effort)
        run: |
          python -m pip install --upgrade pip
          if [ -f backend/requirements.txt ]; then pip install -r backend/requirements.txt; fi

      - name: Import sanity check
        env:
          PYTHONPATH: backend
        run: |
          echo "Checking import of app.main"
          python -c "import app.main; print('app.main import ok')"

  openapi-diff:
    name: Generate OpenAPI and run diff
    runs-on: ubuntu-latest
    needs: import-sanity
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install backend deps (best-effort)
        run: |
          python -m pip install --upgrade pip
          if [ -f backend/requirements.txt ]; then pip install -r backend/requirements.txt; fi

      - name: Generate OpenAPI JSON
        env:
          PYTHONPATH: backend
        run: |
          python -c "import json; from app import main as m; print(json.dumps(m.app.openapi()))" > openapi_current.json

      - name: Upload OpenAPI artifact
        uses: actions/upload-artifact@v4
        with:
          name: openapi-current
          path: openapi_current.json

      - name: Run OpenAPI diff (fails on breaking removals)
        env:
          BASELINE: docs/openapi_baseline.json
          CURRENT: openapi_current.json
        run: |
          python scripts/openapi_diff.py --baseline "$BASELINE" --current "$CURRENT"
