name: Plan → Issues Sync
permissions:
  contents: write
  pull-requests: write
  issues: write
  actions: read
  checks: read
  id-token: write
on:
  push:
    branches: [ main ]
    paths:
      - "data/plan.csv"
    paths-ignore:
      - '.github/workflows/plan-issues-sync.yml'
  schedule:
    - cron: "5 5 * * *"
  workflow_dispatch:
