name: Plan → Issues Sync
permissions:
  contents: write
  pull-requests: write
  issues: write
  actions: read
  checks: read
  id-token: write
on:
  push:
    paths:
      - "data/plan.csv"
  schedule:
    - cron: "5 5 * * *"
  workflow_dispatch:

