name: Snapshot Project Plan
on:
  workflow_dispatch:
  schedule:
    - cron: "0 5 * * *"
  push:
    branches: [ main ]
    paths-ignore:
      - '.github/workflows/snapshot.yml'
      - 'snapshots/**'
      - 'data/plan.csv'
permissions:
  contents: write
  pull-requests: write
jobs:
  snapshot:
    if: github.actor != "github-actions[bot]"
    runs-on: ubuntu-latest
    env:
      BRANCH: bot/snapshot-${{ github.run_id }}
    steps:
      - uses: actions/checkout@v4

      - name: Validate plan.csv
        run: python3 tools/validate_plan_csv.py

      - name: Create branch and commit snapshot
        run: |
          set -euo pipefail
          git switch -c "$BRANCH"
          mkdir -p snapshots
          ts=$(date -u +'%Y-%m-%dT%H-%M-%SZ')
          cp data/plan.csv "snapshots/plan-$ts.csv"
          git add snapshots/*.csv
          git -c user.name="github-actions[bot]" \
              -c user.email="41898282+github-actions[bot]@users.noreply.github.com" \
              commit -m "chore(snapshot): plan at $ts"
          git push -u origin "$BRANCH"

      - name: Open PR
        uses: peter-evans/create-pull-request@v6
        with:
          title: "Snapshot: plan.csv"
          body: "Automated plan snapshot."
          branch: ${{ env.BRANCH }}
