name: Validate project plan CSV
permissions:
  contents: write
  pull-requests: write
  issues: write
  actions: read
  checks: read
  id-token: write

on:
  pull_request:
  push:
    paths:
      - "docs/autorisen_project_plan.csv"
      - "scripts/validate_plan.py"

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install deps
        run: python -m pip install --upgrade pip
      - name: Run CSV validator
        run: python scripts/validate_plan.py
