name: Validate project plan CSV

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - "docs/autorisen_project_plan.csv"
      - "tools/validate_plan_csv.py"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      # Manual checkout of the PR HEAD (no marketplace action)
      - name: Checkout PR head (manual)
        run: |
          set -euo pipefail
          git init .
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git remote add origin "https://github.com/${{ github.repository }}.git"
          # pull_request event always has these:
          SHA="${{ github.event.pull_request.head.sha || github.sha }}"
          git fetch --depth=1 origin "$SHA"
          git checkout --detach "$SHA"

      - name: Python available?
        run: python3 --version

      - name: Run validator
        run: python3 tools/validate_plan_csv.py
